name: Nix
description: Sets up the Nix environment

runs:
  using: composite

  steps:
    - uses: actions/checkout@v2.4.0

    - uses: actions/cache@v2
      env:
        cache-name: nix-cache
      with:
        path: /nix
        key: ${{ runner.os }}-${{ hashFiles('default.nix') }}

    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build
