apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-go-web
  labels:
    app: example-go-web
spec:
  selector:
    matchLabels:
      app: example-go-web
  template:
    metadata:
      labels:
        app: example-go-web
    spec:
      containers:
      - name: example-go-web
        image: example-go-web-image
        ports:
        - containerPort: 8000
