name: Bazel Affected Targets
description: Returns all Bazel targets affected by the changed files

inputs:
  scope:
    description: The scope within which dependencies should be found
    required: false
    default: "//..."

outputs:
  targets:
    description: All targets affected by the changed files
    value: ${{ steps.bazel-rdeps-query.outputs.affected-targets }}

runs:
  using: composite

  steps:
    - uses: actions/checkout@v2

    - id: changed-files
      uses: tj-actions/changed-files@v15
      with:
        separator: +

    - id: bazel-rdeps-query
      shell: bash
      run: |
        echo "Query scope: '${{ inputs.scope }}'"
        query="rdeps(${{ inputs.scope }}, ${{ steps.changed-files.outputs.all_changed_files }})"
        result=$(bazel query "$query" --keep_going | xargs) || echo
        echo "Query result: '$result'"
        echo "::set-output name=affected-targets::$result"
