name: Build

on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      detect_breaking_changes:
        type: boolean
        default: false
        required: false

jobs:
  run-buf-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v0.5.0

      - name: Run Lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'

      - name: Run Breaking Change Detection
        if: ${{ inputs.detect_breaking_changes == 'true' }}
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'proto'
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=proto'
