name: Buildifier

on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      changed_files_only:
        type: boolean
        default: false
        required: false

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Buildifier
        run: go install github.com/bazelbuild/buildtools/buildifier@latest

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v15
        with:
          files: |
            BUILD
            WORKSPACE
            *.bzl
            *.bazel

      - name: Check Build Files
        run: |
          fileset="${{ changed_files_only }}"
          if [[ "$fileset" == "" ]; then
            fileset="-r ."
          fi
          buildifier -mode=check -lint=warn $fileset
