name: Buildifier

on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      changed_files_only:
        type: boolean
        default: false
        required: false

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Nix
        uses: ./.github/actions/nix-os

      - name: Get Changed Files
        id: changed-files
        if: ${{ inputs.changed_files_only }}
        uses: tj-actions/changed-files@v15
        with:
          files: |
            BUILD
            WORKSPACE
            *.bzl
            *.bazel

      - name: Check Build Files
        run: |
          changed_files_only="${{ inputs.changed_files_only }}"
          if [[ "$changed_files_only" == "true" ]]; then
            fileset="${{ steps.changed-files.outputs.all_changed_files }}"
          else
            echo "Executing buildifier on all files."
            fileset="-r ."
          fi
          if [[ "$fileset" != "" ]]; then
            echo "Executing buildifier on: $fileset"
            nix-shell --run "buildifier -mode=check -lint=warn $fileset"
          else
            echo "Skipping buildifier; no files to check"
          fi
