name: Check PR

on:
  pull_request:
    branches: [main]

jobs:
  buf:
    uses: ./.github/workflows/buf.yml
    with:
      detect_breaking_changes: true

  buildifier:
    uses: ./.github/workflows/buildifier.yml
    with:
      changed_files_only: true

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      changed_files_only: true

  bazel-build:
    uses: ./.github/workflows/build.yml
    with:
      affected_targets_only: true

  bazel-test:
    needs: [ bazel-build ]
    uses: ./.github/workflows/test.yml
    with:
      affected_targets_only: true

  tilt-ci:
    needs: [ bazel-build ]
    uses: ./.github/workflows/tilt.yml
