name: Check PR

on:
#  pull_request:
#    branches: [main]

jobs:
  buildifier:
    uses: ./.github/workflows/buildifier.yml
  super-linter:
    uses: ./.github/workflows/lint.yml
  build:
    uses: ./.github/workflows/build.yml
    with:
      affected_targets_only: true
  test:
    needs: [build]
    uses: ./.github/workflows/test.yml
  tilt:
    needs: [build]
    uses: ./.github/workflows/tilt.yml
