name: Check PR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-lint:
    uses: ./.github/workflows/lint.yml
  run-buildifier:
    uses: ./.github/workflows/buildifier.yml
  build-bazel:
    uses: ./.github/workflows/build.yml
  test-tilt:
    needs: [build-bazel]
    uses: ./.github/workflows/tilt.yml
