name: Lint

on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      changed_files_only:
        type: boolean
        default: false
        required: false

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Set up Nix
        uses: ./.github/actions/nix-os

      - name: Generate protos
        run: nix-shell --run "buf generate"

      - uses: github/super-linter/slim@a1e55fad905ce8f35ef9f46a400c7de0bc62d194
        env:
          VALIDATE_ALL_CODEBASE: ${{ !inputs.changed_files_only }}
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint Code
        run: |
          if [[ "${{ inputs.changed_files_only }}" == "true" ]]; then
            rev_flag="--new-from-rev=HEAD~"
          fi
          nix-shell --run "golangci-lint run --config .github/linters/.golangci.yml $rev_flag"
