name: Test

on: [workflow_call]

jobs:
  run-bazel-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Mount Bazel Cache
        uses: ./.github/actions/bazel-cache

      - name: Query Affected Bazel Targets
        id: bazel-affected
        uses: ./.github/actions/bazel-affected

      - name: Run Bazel Tests for Affected Targets
        run: bazel build ${{ steps.bazel-affected.outputs.targets }}
