name: Test

on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      affected_targets_only:
        type: boolean
        default: false
        required: false

jobs:
  run-bazel-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Mount Bazel Cache
        uses: ./.github/actions/bazel-cache

      - name: Run Bazel Tests
        uses: ./.github/actions/bazel-command
        with:
          command: "test"
          affected_targets_only: "${{ inputs.affected_targets_only }}"
