name: Test

on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      affected_targets_only:
        type: boolean
        default: false
        required: false

jobs:
  run-bazel-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Nix
        uses: ./.github/actions/nix-os

      - name: Set up Bazel
        uses: ./.github/actions/bazel-cache

      - name: Generate protos
        run: nix-shell --run "buf generate"

      - name: Run Bazel Tests
        uses: ./.github/actions/bazel-command
        with:
          command: "test"
          affected_targets_only: "${{ inputs.affected_targets_only }}"
