name: Tilt

on: [workflow_call]

jobs:
  run-tilt-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start Kubernetes Cluster
        uses: ./.github/actions/kube-start
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Mount Bazel Cache
        uses: ./.github/actions/bazel-cache

      - name: Test Tilt Environment
        run: tilt ci
