name: Tilt

on: [workflow_call]

jobs:
  run-tilt-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Mount Bazel Cache
        uses: ./.github/actions/bazel-cache

      - name: Test Tilt Environment
        run: |
          minikube start
          tilt ci
          minikube stop
