name: Tilt

on:
  push:
    branches: [main]
  workflow_call:

jobs:
  run-tilt-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Nix
        uses: ./.github/actions/nix-os

      - name: Set up Bazel
        uses: ./.github/actions/bazel-cache

      - name: Generate protos
        run: nix-shell --run "buf generate"

      - name: Test Tilt environment
        run: nix-shell --run "minikube start; tilt ci; minikube stop"
