name: Tilt

on:
  workflow_run:
    workflows: [Build]
    types: 
      - completed

jobs:
  run-tilt-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Kubernetes Tools
        uses: yokawasa/action-setup-kube-tools@v0.8.0

      - name: Start K8s Cluster
        run: minikube start

      - name: Mount Bazel Cache
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-development

      - name: Test Tilt Environment
        run: tilt ci
