name: Tilt

on:
  push:
    branches: [main]
  workflow_call:

jobs:
  run-tilt-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Kubernetes Tools
        uses: yokawasa/action-setup-kube-tools@v0.8.0

      - name: Mount Bazel Cache
        uses: ./.github/actions/bazel-cache

      - name: Test Tilt Environment
        run: |
          minikube start
          tilt ci
          minikube stop
